### ISSUE TITLE
LookupViaCity returning wrong info

### ISSUE THREAD

**Issue by IsraelGboluwaga** [kevinroberts/city-timezones#8]
The lookUpViaCity method returns `America/Toronto` as timezone for `London`.

**Comment by Rotimi-Best** [comment]
I tested it and can validate this issue.

This issue is because the search picks every field where London is mentioned and the first instance where London was mentioned is related to _London Canada_ [view on timedate.com](https://www.timeanddate.com/worldclock/canada/london) but I guess it should be _London, England, United Kingdom_ [view on timedate.com](https://www.timeanddate.com/worldclock/uk/london).

To fix this issue a new timezone in the cityMap.json file there needs to be added an extra object for London England as well.

**Comment by kevinroberts** [comment]
Ah the multiple cities with the same name issue. I can take a look and update the json file.

**Comment by Rotimi-Best** [comment]
@kevinroberts That would be really helpful. Thanks.

**Comment by kevinroberts** [comment]
So multiple London's exist in the JSON data store, you actually get 6 entries when you search London.
London, United Kingdom is in this list. This is up to how you implement the logic on your end to find the city you are intending to match. 
  {
    "city": "London",
    "city_ascii": "London",
    "lat": 51.49999473,
    "lng": -0.116721844,
    "pop": 7994104.5,
    "country": "United Kingdom",
    "iso2": "GB",
    "iso3": "GBR",
    "province": "Westminster",
    "timezone": "Europe/London"
  },
